trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Build_And_Deploy
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: npm install
        workingDirectory: "admin-user-service"
        displayName: "Install Admin User Service Dependencies"

      - script: npm run build
        workingDirectory: "admin-user-service"
        displayName: "Build Admin User Service"

      - script: npm install
        workingDirectory: "notification-service"
        displayName: "Install Notification Service Dependencies"

      - script: npm run build
        workingDirectory: "notification-service"
        displayName: "Build Notification Service"

      - script: npm install
        workingDirectory: "user-service"
        displayName: "Install User Service Dependencies"

      - script: npm run build
        workingDirectory: "user-service"
        displayName: "Build User Service"

      - task: AzureWebApp@1
        inputs:
          azureSubscription: "<Azure-Service-Connection>"
          appName: "<App-Service-Name>"
          package: "$(Build.ArtifactStagingDirectory)/**/*.zip"
        displayName: "Deploy to Azure"
